server:
  port: 7011

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: enba_test_virtual_host
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual



