server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #    显示指定使用的连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: true
      initial-size: 5
      min-idle: 10
      max-active: 100
      query-timeout: 300
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
      stat-view-servlet:
        #        http://localhost:8085/druid/login.html 可访问druid可视化界面
        enabled: true
        login-username: enba
        login-password: 123456

mybatis-plus:
  #  global-config:
  #    db-config:
  #      id-type: auto
  #      logic-delete-value: 1
  #      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.enba.druid.entity