server:
  port: 9102

logging:
  config: classpath:logback.xml
xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:9100/xxl-job-admin
    executor:
      address: ''
      appname: enba-executor-sample
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9998
