server:
  port: 8060

spring:
  application:
    name: @project.artifactId@

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:8059/eureka/
  instance:
    prefer-ip-address: true